# https://wiki.debian.org/Nginx/DirectoryStructure
#
# In most cases, administrators will remove this file from sites-enabled/ and
# leave it as reference inside of sites-available where it will continue to be
# updated by the nginx packaging team.
#
# This file will automatically load configuration files provided by other
# applications, such as Drupal or Wordpress. These applications will be made
# available underneath a path with that package name, such as /drupal8.
#
# Please see /usr/share/doc/nginx-doc/examples/ for more detailed examples.
##

# Default server configuration
#

server {
        index index.htm index.nginx-debian.html index.html;
        server_name gomi-guesser.sunasuna.cafe;

        access_log /var/log/nginx/gomi-guesser.sunasuna.cafe.access.log;
        error_log /var/log/nginx/gomi-guesser.sunasuna.cafe.error.log;

        location / {
                # First attempt to serve request as file, then
                # as directory, then fall back to displaying a 404.
                # try_files $uri $uri/ =404;
                proxy_set_header X-Real-IP $remote_addr;
                proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
                proxy_set_header Host $host;
                proxy_pass http://127.0.0.1:8080/;
        }


    listen 443 ssl; # managed by Certbot
    ssl_certificate /etc/letsencrypt/live/gomi-guesser.sunasuna.cafe/fullchain.pem; # managed by Certbot
    ssl_certificate_key /etc/letsencrypt/live/gomi-guesser.sunasuna.cafe/privkey.pem; # managed by Certbot
    include /etc/letsencrypt/options-ssl-nginx.conf; # managed by Certbot
    ssl_dhparam /etc/letsencrypt/ssl-dhparams.pem; # managed by Certbot

}


server {
    if ($host = gomi-guesser.sunasuna.cafe) {
        return 301 https://$host$request_uri;
    } # managed by Certbot


        server_name gomi-guesser.sunasuna.cafe;
    listen 80;
    return 404; # managed by Certbot


}