// Typelizer digest e5e3908a4159eb09ade5ddd0fee98b61
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
export type { default as Municipality } from './Municipality'
export type { default as Prefecture } from './Prefecture'
