// Typelizer digest da9f0577fd2e45d18b755a5086df6294
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.

type Municipality = {
  id: number;
  eng_name: string;
  kanji_name: string;
  kana_name: string;
  municipality_type: string;
  prefecture_id: number;
  updated_at: string;
  created_at: string;
}

export default Municipality;
