// Typelizer digest 3e2b07287d3b78b4b7f3e6a7b3405411
//
// DO NOT MODIFY: This file was automatically generated by Typelizer.
import type { Municipality } from "@/types/serializers";

type Prefecture = {
  id: number;
  eng_name: string;
  kanji_name: string;
  kana_name: string;
  updated_at: string;
  created_at: string;
  municipalities: Array<Municipality>;
};

export default Prefecture;
